name = "Kami Chan Optimized"
author = "mja00"
version = "21.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c2f9c1ae7fd1d4d6dd318efd85e3968ab5f928c284d785e949373c993f37786"

[versions]
fabric = "0.19.1"
minecraft = "26.1.2"

[options]
acceptable-game-versions = [
    "26.1.1",
]
